directories:
  output: distnew
  buildResources: build
appId: com.yourcompany.yourapp
productName: YourApp
files:
  - filter:
      - distnew/**/*
      - node_modules/**/*
      - main.js
win:
  target: nsis
mac:
  target: dmg
electronVersion: 29.1.6
